version: '3.8'  # You can specify your desired Docker Compose version

services:
  backend:
    build: ./backend
    container_name: myaje-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./backend:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: myaje-frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./frontend:/app
    command: npm run dev
    env_file:
      - .env
  
  postgres:
    image: postgres:17  
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alegeaa
      POSTGRES_DB: myaje
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
  
  nginx:
    image: nginx:latest
    container_name: myaje-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
  
volumes:
  postgres_data:  
    driver: local   
