"""Added admin_notes to Restock Requests model

Revision ID: 085a3aaa2f5f
Revises: c74de5daa268
Create Date: 2024-12-30 01:40:33.711528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085a3aaa2f5f'
down_revision: Union[str, None] = 'c74de5daa268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restock_requests', sa.Column('admin_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restock_requests', 'admin_notes')
    # ### end Alembic commands ###
