"""model errors fixed again

Revision ID: 17954fb1afe7
Revises: d5cebfe8103b
Create Date: 2025-01-12 10:57:54.653375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17954fb1afe7'
down_revision: Union[str, None] = 'd5cebfe8103b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
