"""accounts fix

Revision ID: 183a0be29acb
Revises: 13b562921fe9
Create Date: 2025-01-12 10:04:52.829729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '183a0be29acb'
down_revision: Union[str, None] = '13b562921fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('banking_automations_destination_bam_account_id_fkey', 'banking_automations', type_='foreignkey')
    op.create_foreign_key(None, 'banking_automations', 'bank_accounts', ['destination_bam_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'banking_automations', type_='foreignkey')
    op.create_foreign_key('banking_automations_destination_bam_account_id_fkey', 'banking_automations', 'external_accounts', ['destination_bam_account_id'], ['id'])
    # ### end Alembic commands ###
