"""Add feedback_notes to Feedback model

Revision ID: 246bf10a2061
Revises: fd85bcd5c82f
Create Date: 2024-12-20 03:20:43.807424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246bf10a2061'
down_revision: Union[str, None] = 'fd85bcd5c82f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('admin_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'admin_notes')
    # ### end Alembic commands ###
