"""Notification metadata spelling error fixed

Revision ID: 3e49c861f3e7
Revises: b15cf129cc93
Create Date: 2025-01-09 11:22:14.369981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e49c861f3e7'
down_revision: Union[str, None] = 'b15cf129cc93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('notification_metadata', sa.JSON(), nullable=True))
    op.drop_column('notifications', 'notificaiton_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('notificaiton_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('notifications', 'notification_metadata')
    # ### end Alembic commands ###
