"""reference for transaction cant be unique

Revision ID: 462d472ff05b
Revises: 60e308bdf900
Create Date: 2025-01-08 13:25:46.782718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462d472ff05b'
down_revision: Union[str, None] = '60e308bdf900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_reference_key', 'transactions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('transactions_reference_key', 'transactions', ['reference'])
    # ### end Alembic commands ###
