"""Loan acceptance and rejection

Revision ID: 49a3b627f704
Revises: 688084c11b97
Create Date: 2025-01-11 22:39:27.748768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a3b627f704'
down_revision: Union[str, None] = '688084c11b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'rejection_reason')
    # ### end Alembic commands ###
