"""payments stuff

Revision ID: 5496e1a34a5e
Revises: 17954fb1afe7
Create Date: 2025-01-14 12:57:15.832785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5496e1a34a5e'
down_revision: Union[str, None] = '17954fb1afe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', name='payout_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('marketplace_orders', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'marketplace_orders', 'payments', ['payment_id'], ['id'])
    op.add_column('payments', sa.Column('marketplace_order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'marketplace_orders', ['marketplace_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'marketplace_order_id')
    op.drop_constraint(None, 'marketplace_orders', type_='foreignkey')
    op.drop_column('marketplace_orders', 'payment_id')
    op.drop_table('payouts')
    # ### end Alembic commands ###
