"""Pool locking

Revision ID: 60e308bdf900
Revises: e71e345e7693
Create Date: 2025-01-08 10:32:21.538735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e308bdf900'
down_revision: Union[str, None] = 'e71e345e7693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_pools', sa.Column('is_locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_pools', 'is_locked')
    # ### end Alembic commands ###
