"""automations

Revision ID: 688084c11b97
Revises: 819533c203db
Create Date: 2025-01-11 11:29:57.551389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688084c11b97'
down_revision: Union[str, None] = '819533c203db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banking_automations', sa.Column('destination_account_id', sa.Integer(), nullable=True))
    op.add_column('banking_automations', sa.Column('destination_bam_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'banking_automations', 'external_accounts', ['destination_account_id'], ['id'])
    op.create_foreign_key(None, 'banking_automations', 'external_accounts', ['destination_bam_account_id'], ['id'])
    op.drop_column('banking_automations', 'destination_account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banking_automations', sa.Column('destination_account', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'banking_automations', type_='foreignkey')
    op.drop_constraint(None, 'banking_automations', type_='foreignkey')
    op.drop_column('banking_automations', 'destination_bam_account_id')
    op.drop_column('banking_automations', 'destination_account_id')
    # ### end Alembic commands ###
