"""bank account id for automations and loans

Revision ID: 819533c203db
Revises: 8940672f9808
Create Date: 2025-01-10 15:29:39.403254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '819533c203db'
down_revision: Union[str, None] = '8940672f9808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banking_automations', sa.Column('bank_account_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'banking_automations', 'bank_accounts', ['bank_account_id'], ['id'])
    op.add_column('loans', sa.Column('bank_account_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'loans', 'bank_accounts', ['bank_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_column('loans', 'bank_account_id')
    op.drop_constraint(None, 'banking_automations', type_='foreignkey')
    op.drop_column('banking_automations', 'bank_account_id')
    # ### end Alembic commands ###
