"""Model improvements for automations and loans

Revision ID: 8940672f9808
Revises: 8e7dcad49c1b
Create Date: 2025-01-10 11:24:40.399031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8940672f9808'
down_revision: Union[str, None] = '8e7dcad49c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banking_automations', sa.Column('percentage', sa.Float(), nullable=True))
    op.add_column('banking_automations', sa.Column('destination_pool_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'banking_automations', 'financial_pools', ['destination_pool_id'], ['id'])
    op.add_column('orders', sa.Column('buyer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['buyer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'buyer_id')
    op.drop_constraint(None, 'banking_automations', type_='foreignkey')
    op.drop_column('banking_automations', 'destination_pool_id')
    op.drop_column('banking_automations', 'percentage')
    # ### end Alembic commands ###
