"""rejection reason for money requests

Revision ID: a8368ece6780
Revises: 08bd32c549b6
Create Date: 2025-01-08 19:36:32.227176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8368ece6780'
down_revision: Union[str, None] = '08bd32c549b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('money_requests', sa.Column('rejection_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('money_requests', 'rejection_reason')
    # ### end Alembic commands ###
